### ISSUE TITLE
TOX : Unit tests failed , ERROR collecting tests/unit/test_ingest.py

### ISSUE THREAD

**Issue by wahbi** [neicnordic/LocalEGA#14]
### Expected Behavior
Unit tests failed 

### Current Behavior
=========================================================================================== ERRORS ===========================================================================================
_________________________________________________________________________ ERROR collecting tests/unit/test_ingest.py _________________________________________________________________________
ImportError while importing test module '/home/wahbi/LocalEGA/tests/unit/test_ingest.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/unit/test_ingest.py:2: in <module>
    from lega.ingest import main, work
lega/ingest.py:24: in <module>
    from legacryptor.crypt4gh import get_header
.tox/unit_tests/lib/python3.7/site-packages/legacryptor/crypt4gh.py:16: in <module>
    import pgpy # Simply used to encrypt/decrypt the records, all in memory.
.tox/unit_tests/lib/python3.7/site-packages/pgpy/__init__.py:5: in <module>
    from .pgp import PGPKey
.tox/unit_tests/lib/python3.7/site-packages/pgpy/pgp.py:45: in <module>
    from .packet import Key
.tox/unit_tests/lib/python3.7/site-packages/pgpy/packet/__init__.py:9: in <module>
    from .packets import *  # NOQA
.tox/unit_tests/lib/python3.7/site-packages/pgpy/packet/packets.py:18: in <module>
    from .fields import DSAPriv, DSAPub, DSASignature
.tox/unit_tests/lib/python3.7/site-packages/pgpy/packet/fields.py:30: in <module>
    from cryptography.hazmat.primitives.asymmetric import ed25519
E   ImportError: cannot import name 'ed25519' from 'cryptography.hazmat.primitives.asymmetric' (/home/wahbi/LocalEGA/.tox/unit_tests/lib/python3.7/site-packages/cryptography/hazmat/primitives/asymmetric/__init__.py)
====================================================================================== 1 error in 0.32s ======================================================================================
ERROR: InvocationError for command /home/wahbi/LocalEGA/.tox/unit_tests/bin/coverage run -m pytest -x tests/unit (exited with code 1)
__________________________________________________________________________________________ summary ___________________________________________________________________________________________
  flake8: commands succeeded
ERROR:   unit_tests: commands failed

### Steps to Reproduce

1.
2.
3.
4.

### Context (Environment)

==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.7.3, pytest-5.2.1, py-1.8.0, pluggy-0.13.0
cachedir: .tox/unit_tests/.pytest_cache
rootdir: /home/wahbi/LocalEGA
plugins: cov-2.8.1
collected 29 items / 1 errors / 28 selected

**Comment by blankdots** [comment]
this is reported in #11 we will track that there.
