### ISSUE TITLE
Uploading a file disables archived files with the same name

### ISSUE THREAD

**Issue by jonandernovella** [neicnordic/LocalEGA#24]
### Expected Behavior
When uploading a file, files in the archive that had the same name in the inbox should not be disabled.

### Current Behavior
The already archived file gets disabled.

This disabling happens somewhere in ingestion/verify or finalize.

### Steps to Reproduce

1. Upload a file with name <name>
2. Ingest it into the archive and make it ready
3. Upload a file with the same name
4. Ingest it into the archive and make it ready

The first file is disabled.

**Comment by viklund** [comment]
It's this that causes it:

https://github.com/neicnordic/LocalEGA-db/tree/master/initdb.d/01_main.sql#L164-L168

**Comment by pontus** [comment]
Can someone verify that I've correctly understood; it's supported to have "any number" of files with the same user, filepath?
