### ISSUE TITLE
Exclude the header blob from the messages

### ISSUE THREAD

**Issue by dtitov** [neicnordic/LocalEGA#46]
### Description
I realized that one of the messages published internally (to the `archived` queue) contains the file header blob. This is not very secure (in case the broker gets compromised somehow, this message might get leaked), and also there's no practical need for this: headers are stored in the database anyway, so all the microservices have direct access to them.

### Proposed solution
Remove the header blob from the corresponding messages.

### Definition of Done
Make sure that messages that are circulated in the RabbitMQ (even internally) don't contain the header blobs.

**Comment by viklund** [comment]
`verify` is currently reading the header from the message. So it needs to be updated to read it from the database instead.

https://github.com/neicnordic/LocalEGA/blob/master/lega/verify.py#L98
